@startuml
'https://plantuml.com/class-diagram
' https://blog.csdn.net/scoryy/article/details/123667176

' 结构对象 ObjectStructure
' 元素  Element
' 上面是稳定结构

' 访问者 Visitor
' 上面是变化结构


interface Visitor {
    + visit(ConcreteElementA element):void
    + visit(ConcreteElementB element):void
}
class ConcreteVisitorA implements Visitor{
    + visit(ConcreteElementA element):void
    + visit(ConcreteElementB element):void
}
class ConcreteVisitorB implements Visitor{
    + visit(ConcreteElementA element):void
    + visit(ConcreteElementB element):void
}


abstract class Element {
    + accept(Visitor visitor):void
}
class ConcreteElementA extends Element{
    + accept(Visitor visitor):void
    + operationA()
}
class ConcreteElementB extends Element{
    + accept(Visitor visitor):void
    + operationB()
}
class ObjectStructure{
    - list:List<Element>

    + accept(Visitor visitor):void

    + add(Element element)
    + remove(Element element)
}


' 分组
together {
    abstract class Element
    class ConcreteElementA
    class ConcreteElementB
    class ObjectStructure
}


ObjectStructure o--> Element : 组合、依赖
Client --> Visitor : 依赖
Client --> ObjectStructure : 依赖


@enduml