@startuml
'https://plantuml.com/class-diagram

class Event
class EventSource
interface IListener
class ListenerImpl


EventSource o--> IListener : 1）向事件源注册监听器 3）事件源 通知监听器
Event o--> EventSource : 2）客户端触发 事件源 产生事件
IListener <|-- ListenerImpl
IListener --> Event : 4）监听器处理事件


@enduml